FROM ubuntu:26.04 AS base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y install gosu swig python3-wxgtk4.0 python3-pip python3-minimal x11-xserver-utils wget qtbase5-dev libsdl2-2.0-0 libusb-1.0-0-dev portaudio19-dev libasound2-dev pulseaudio libpulse-dev\
  && apt-get -y install pkg-config git cmake build-essential nasm wget python3-setuptools libusb-1.0-0-dev  python3-dev python3-pip python3-numpy python3-scipy libglew-dev libtbb-dev \
     libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev ffmpeg x264 x265 libportaudio2 portaudio19-dev \
     python3-opencv libopencv-dev libeigen3-dev curl libxml2-dev libglib2.0-dev cmake libusb-1.0-0-dev gobject-introspection \
     libgtk-3-dev gtk-doc-tools  xsltproc libgstreamer1.0-dev \
     libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good \
     libgirepository-2.0-dev gir1.2-girepository-2.0-dev gettext ninja-build vlc libvlc-dev libjpeg-turbo8-dev\
     libturbojpeg0-dev meson \
     unzip libsdl-dev \
  && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/pupil-labs/libuvc \
  && cd libuvc \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make && make install \
  && cd ../../ && rm -Rf libuvc

ARG ARAVIS_VERSION=0.8.36

# for aravis in docker see https://github.com/AravisProject/aravis/issues/509
RUN cd /tmp/ \
  && wget https://github.com/AravisProject/aravis/archive/refs/tags/${ARAVIS_VERSION}.tar.gz \
  && tar -xzf ${ARAVIS_VERSION}.tar.gz \
  && cd aravis-$ARAVIS_VERSION \
  && meson build && cd build \
  && ninja && ninja install \
  && cd ../.. && rm -Rf aravis-$ARAVIS_VERSION ${ARAVIS_VERSION}.tar.gz

# Install uv by copying the binary directly from the official image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set performance optimization environment variables
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
RUN uv venv /src/.venv

RUN mkdir -p /src/ && cd /src \
  && git clone https://github.com/courtois-neuromod/pupil.git \
  && cd pupil \
  && git checkout testing \
  && . /src/.venv/bin/activate \
  && uv pip install --no-cache-dir -r requirements.txt

COPY pulse-client.conf /etc/pulse/client.conf

RUN chown -R 1000:1000 /src/pupil

ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/x86_64-linux-gnu

#RUN source /src/.venv/bin/activate \
#  && uv pip install --no-cache-dir --no-binary :all: --force-reinstall pyzmq

ENV GI_TYPELIB_PATH=/usr/local/lib/x86_64-linux-gnu/girepository-1.0/

RUN cd /src/ \
  && wget https://github.com/courtois-neuromod/task_stimuli/archive/refs/heads/update_deps.zip \
  && unzip update_deps.zip \
  && mv task_stimuli-* task_stimuli

FROM base AS build
RUN . /src/.venv/bin/activate \
  && uv pip install --no-cache-dir https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.5-cp314-cp314-linux_x86_64.whl

RUN . /src/.venv/bin/activate \
  && echo 'ffpyplayer' > /tmp/excludes.txt \
  && echo 'scipy==1.18' > /tmp/constraints.txt \
  && uv pip install --no-cache-dir -r /src/task_stimuli/requirements.txt --excludes /tmp/excludes.txt --constraints /tmp/constraints.txt
COPY ./.env.docker /src/task_stimuli/.env

RUN . /src/.venv/bin/activate \
  && uv pip install  --no-cache-dir dotenv
#  && uv pip install  --no-cache-dir python-vlc==3.0.11115

WORKDIR /src/task_stimuli/

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
